version: '3.1'
services:
  db:
    image: 'postgres:latest'
    container_name: "postgresql"
    volumes:
      - ./pg_data:/var/lib/postgresql/data 
      #- ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=Abc.1234%
      - POSTGRES_USER=pgadmin
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/db  
    ports:
      - 5432:5432
    networks:
      - postgres
  servercentos:    
    build: 
      context: ./python
      dockerfile: Dockerfile
    container_name: "servercentos"
    volumes:
      - ./tmp/rawdata:/usr/rawdata
    restart: always
    entrypoint: /bin/bash
    depends_on:
      - db  
    networks:
      - postgres
  nodejs:
    container_name: "nodejs"
    build: 
      context: ./node/app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./node/app
      - ./node/app/node_modules:/node/app/node_modules
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - postgres 
    command: "npm run start"
    
      

      
networks:
  postgres:
    driver: bridge
volumes:
  node_modules: {}